server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Endereço do eureka
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sleuth:
    sampler:
      probability: 1.0 # Porcentagem de informações que serão feitas log (1.0 = 100%) Obs: Em produção deve ser 0.05
springdoc:
  #show-actuator: true
  api-docs:
    path: cambio-service/v3/api-docs