server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Endereço do eureka
resilience4j:
  bulkhead: # @Bulkhead
    instances:
      default:
        max-concurrent-calls: 10        
  ratelimiter: # @RateLimiter
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry: # @Retry
    instances:
      foo-bar:
        max-attempts: 5 # Quantas tentativas o retry vai fazer
        wait-duration: 1s # Tempo de espera entre cada tentativa
        enable-exponential-backoff: true # Tempo entre cada tentiva cresce exponencialmente
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jackson:
    default-property-inclusion: NON_NULL # Não irá serializar uma propriedade JSON null
    serialization:
      fail-on-empty-beans: false  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sleuth:
    sampler:
      probability: 1.0 # Porcentagem de informações que serão feitas log (1.0 = 100%) Obs: Em produção deve ser 0.05
  #zipkin:
    #base-url: http://localhost:9411     Se alterar a porta padrão (9411), tem que especificar a base url
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs