server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Configura o Gateway para criar rotas automaticamente com base em serviços registrados com clientes de descoberta como o Eureka
          #lower-case-service-id: true
      routes:
      - id: cambio-service
        uri: lb://cambio-service
        predicates:
        - Path=/cambio-service/**
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/book-service/**
      - id: openapi
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs # Rescreve o caminho /v3/api-docs/{SERVICE_NAME} como /{SERVICE_NAME}/v3/api-docs,
  sleuth:
    sampler:
      probability: 1.0 # Porcentagem de informações que serão feitas log (1.0 = 100%) Obs: Em produção deve ser 0.05