server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Indica que o gateway habilita a função de registro e descoberta de serviço, e o spring cloud gateway cria automaticamente um roteador para cada serviço com base na descoberta de serviço, e esse roteador irá comece com o nome do serviço.
          lower-case-service-id: true
