server:
  port: 8888
spring:
  application:
    name: greeting-config-server
  #profiles:
    #active:    
    #- native # Vai ler as configurações da máquina
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GustavoSC1/greeting-config-server
          #username: username
          #password: password
          default-label: main
          search-paths:
          - 'greeting-service*'